# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - hhvm-nightly


# Specify versions of WordPress to test against
# WP_VERSION = WordPress version number (use "master" for SVN trunk)
# WP_MULTISITE = whether to test multisite (use either "0" or "1")
env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=4.4 WP_MULTISITE=0
    - WP_VERSION=3.8.0 WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=4.4 WP_MULTISITE=1
    - WP_VERSION=3.8.0 WP_MULTISITE=1


# Next we define our matrix of additional build configurations to test against.
# The versions listed above will automatically create our first configuration,
# so it doesn't need to be re-defined below.

# WP_VERSION specifies the tag to use. The way these tests are configured to run
# requires at least WordPress 3.8. Specify "master" to test against SVN trunk.

# Note that Travis CI supports listing these above to automatically build a
# matrix of configurations, but we're being nice here by manually building a
# total of four configurations even though we're testing 4 versions of PHP
# along with 2 versions of WordPress (which would build 8 configs otherwise).
# This takes half as long to run while still providing adequate coverage.

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

# Clones WordPress and configures our testing environment.
before_script:
#    - export PLUGIN_SLUG=$(basename $(pwd))
#    - git clone https://github.com/tierra/wordpress.git /tmp/wordpress
#    - git clone . "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
#    - cd ..
#    - mv $PLUGIN_SLUG "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
#    - cd /tmp/wordpress
#    - git checkout $WP_VERSION
#    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
#    - cp wp-tests-config-sample.php wp-tests-config.php
#    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
#    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
#    - sed -i "s/yourpasswordhere//" wp-tests-config.php
#    - cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"

script: phpunit
